name: Deploy to Azure Storage

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - uses: bacongobbler/azure-blob-storage-upload@main
      with:
        source_dir: ./source/public
        container_name: $web
        connection_string: ${{ secrets.AZURE_STORAGE_W9MAINSITE }}
        extra_args: '--destination-path ./'
        overwrite: true
